spring:
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_book_appointment?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: aa123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    mode: html
    prefix: classpath:/templates/
  mvc:
    static-path-pattern: /static/**

mybatis:
  type-aliases-package: com.example.bookappointment.domain
  mapper-locations: classpath:mapper/*.xml


